packages:
  - .

allowBuilds:
  astro-papyrus@https://codeload.github.com/marcelofpfelix/papyrus/tar.gz/1113b431bc35f8c176ed71c58c800869edbd01b7: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
