packages:
  - .

allowBuilds:
  astro-papyrus@https://codeload.github.com/marcelofpfelix/papyrus/tar.gz/23d686ae0932bf38c9e6487e58d26edf1704c5fc: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
